#!/usr/bin/env bash

# Install brew package manager
if [[ "$(which -s brew > /dev/null 2>&1; echo $?)" -ne 0 ]]; then
  echo | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  log.success "✅  Homebrew already installed: $(brew -v), updating instead!"
  brew update
fi

# Install brew and all apps on Brewfile, Caskfile and Masfile
brew update-reset

# Update all brew Taps
brew tap heroku/brew

log.info "1️⃣ ⚙️  Installing all Brewfile dependencies"
brew bundle install --no-upgrade --verbose --file=$DIRECTORY/install/Brewfile

log.info "2️⃣ ⚙️  Installing all Caskfile dependencies"
brew bundle install --no-upgrade --verbose --file=$DIRECTORY/install/Caskfile

log.info "3️⃣ ⚙️  Installing all Masfile dependencies"
brew bundle install --no-upgrade --verbose --file=$DIRECTORY/install/Masfile

# Finally just upgrade everything (Taps and Formulas)
brew upgrade

# Remove brew and cask old formulas
brew cleanup
log.success "✅  All brew files installed!"
