tap "homebrew/bundle"
tap "homebrew/core"

# Display directories as trees (https://www.geeksforgeeks.org/tree-command-unixlinux/) 
brew "tree"

# Download files over network (https://www.computerhope.com/unix/wget.htm)
brew "wget"

# Tool for managing dock items (https://github.com/chilcote/outset/wiki/Dockutil)
brew "dockutil"

# Install ZShell (https://sourabhbajaj.com/mac-setup/iTerm/zsh.html)
brew "zsh"

# Mac App Store command-line interface (https://github.com/mas-cli/mas)
brew "mas"

# Expose localhost to the internet and capture traffic for replay (https://ngrok.com/)
brew "ngrok"