#!/usr/bin/env bash

# Setup path to dockutil
dockutil --no-restart --remove all
# The "--no-restart" flag is to prevent MacOS dock from restarting each change.
dockutil --no-restart --add "/Applications/Google Chrome.app"
dockutil --no-restart --add "/Applications/Franz.app"
dockutil --no-restart --add "/Applications/Utilities/Terminal.app"
# dockutil --no-restart --add "/Applications/iTerm.app"
dockutil --no-restart --add "/Applications/Visual Studio Code.app"
dockutil --no-restart --add "/Applications/Evernote.app"
dockutil --no-restart --add "/Applications/PyCharm.app"
dockutil --no-restart --add "/Applications/Spotify.app"

# We just don't put it in the last command to apply all changes.
dockutil --add "~/Downloads" --view fan

# Another alternative would be to just kill the Dock itself after all changes were made
# killall Dock

log.success "Dock $(dockutil --version) shortcuts configured!"
