#!/usr/bin/env bash

# Make sure exercism is installed
if brew ls --versions exercism > /dev/null; then
    # The package is installed
    exercism version
    # Setup exercism on expected folder
    exercism configure --token=$EXERCISM_TOKEN --workspace /Users/$USER/projects/Exercism
    # Pull repo from github
    git clone git@github.com:andreffs18/Exercism.git ~/projects
else
  log.fail "🥴 Exercism was not installed"
fi


