#!/usr/bin/env bash

# Download oh-my-zsh framework
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Setup defined shell on terminal
chsh -s $(which zsh)

# Replace installed .zshrc file with my own
# ~/.zshrc

# Print zsh version
log.success "$(zsh --version)"
