#!/usr/bin/env bash

# Download oh-my-zsh framework
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh) -s --unattended"

# Setup defined shell on terminal
chsh -s $(which zsh)

# Overwrite installed .zshrc from oh-my-zsh with my own
ln -sfv $DIRECTORY/config/system/.zshrc ~

# Download plugins
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-completions.git ~/.oh-my-zsh/custom/plugins/zsh-completions
git clone https://github.com/zpm-zsh/tmux.git ~/.oh-my-zsh/custom/plugins/tmux
git clone https://github.com/mattbangert/kubectl-zsh-plugin.git ~/.oh-my-zsh/custom/plugins/kubectl-zsh-plugin

# Print zsh version
log.success "Installed oh-my-zsh on $(zsh --version)!"
