#!/usr/bin/env bash

# Download oh-my-zsh framework
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh) --skip-chsh"

# Setup defined shell on terminal
chsh -s $(which zsh)

# Overwrite installed .zshrc from oh-my-zsh with my own
ln -sfv $DIRECTORY/config/system/.zshrc ~

# Print zsh version
log.success "Installed oh-my-zsh on $(zsh --version)!"
