#!/usr/bin/env bash

# Make sure keybase is installed so we can pull these secrets
# if brew cask ls --versions keybase > /dev/null; then
if keybase version > /dev/null; then
    # Login and pull all secrets to local machine
    keybase login
    keybase fs cp -r keybase://private/andreffs18/.ssh ~/.ssh

    # Set my ~/.ssh/id_rsa as my private key to the SSH Agent
    ssh-add --apple-use-keychain  ~/.ssh/id_rsa

    # Check github connection
    ssh -T git@github.com
else
  log.fail "🥴 Keybase was not installed"
fi
